spring:
  datasource:
      url: jdbc:h2:file:./.local/datasource/db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      username: sa
      password: 123456
  flyway:
    validate-on-migrate: false
  h2:
    console:
      enabled: true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.6-plus
          multi_model: true
          enable_thinking: true
      embedding:
        options:
          model: text-embedding-v2
#    ollama:
#      chat:
#        options:
#          model: qwen3
#      embedding:
#        options:
#          model: qwen3-embedding
#      base-url: http://localhost:11434
#    vectorstore:
#      redis:
#        initialize-schema: true
#        index-name: custom-index
#        prefix: custom-prefix
#      qdrant:
#        host: localhost
#        port: 6334
##        collection-name: custom-collection-name
#        collection-name: qwen-collection-name
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers-dev.json
    loom:
      agent:
        rag:
          similarityThreshold: 0.50
          top-k: 4
          defaultPromptTemplate: |
            Context information is below.
            
            ---------------------
            {context}
            ---------------------
            
            Given the context information and no prior knowledge, answer the query.
            
            Follow these rules:
            
            1. If the answer is not in the context, just say that you don't know.
            2. Avoid statements like "Based on the context..." or "The provided information...".
            
            Query: {query}
            
            Answer:
          defaultEmptyContextPromptTemplate: |
            The user query is outside your knowledge base.
            Politely inform the user that you can't answer it.
        mcps:
          - name: spring-ai-mcp-client - bing-search
            title: 必应搜索
            description: 一个集成了微软必应搜索API的模型上下文协议服务
            default-selected: true
          - name: spring-ai-mcp-client - @tokenizin-agency/mcp-npx-fetch
            title: 网页内容抓取
            description: 一个强大的MCP服务器,可以轻松地将网页内容抓取并转换为各种格式(HTML、JSON、Markdown、纯文本)
            default-selected: true
            tools:
              - name: fetch_html
                description: 获取网页内容，并以 HTML 格式返回
              - name: fetch_markdown
                description: 取网页内容，并以 Markdown 格式返回
              - name: fetch_txt
                description: 取网页内容，并以纯文本格式返回（不含 HTML）
              - name: fetch_json
                description: 从指定 URL 获取 JSON 文件
          - name: spring-ai-mcp-client - sequential-thinking
            title: 顺序思维
            description: 一种MCP服务器实现，提供动态且反射性的解决问题的工具
            tools:
              - name: sequentialthinking
                description: 本工具通过可适应与演进的灵活思维流程，协助对问题进行深入分析
          - name: spring-ai-mcp-client - memory
            title: 记忆
            description: 使用本地知识图谱实现持久化记忆
            tools:
              - name: create_entities
                description: 在知识图谱中创建多个新实体
              - name: create_relations
                description: 在知识图谱的实体之间创建多个新关系
              - name: add_observations
                description: 向知识图谱中现有实体添加新的观察信息
              - name: delete_entities
                description: 从知识图谱中删除多个实体及其关联的关系
              - name: delete_observations
                description: 从知识图谱的实体中删除特定的观察信息
              - name: delete_relations
                description: 从知识图谱中删除多个关系
              - name: read_graph
                description: 读取整个知识图谱
              - name: search_nodes
                description: 基于查询在知识图谱中搜索节点
              - name: open_nodes
                description: 通过名称打开知识图谱中的特定节点
          - name: spring-ai-mcp-client - cn-weather-mcp
            title: 中国天气
            description: 自研中国城市实时天气服务
          - name: spring-ai-mcp-client - http-mcp
            title: HTTP 客户端
            description: HTTP客户端MCP服务，提供通用HTTP请求功能
          - name: spring-ai-mcp-client - playwright
            title: Playwright
            description: 通过结构化可访问性快照与网页交互
          - name: spring-ai-mcp-client - chrome-devtools
            title: Chrome DevTools
            description: 控制和检查Chrome浏览器，实现自动化操作和调试
          - name: spring-ai-mcp-client - context7
          - name: spring-ai-mcp-client - git-mcp-server
          - name: spring-ai-mcp-client - mcp-server-docker
          - name: spring-ai-mcp-client - desktop-commander
        skills:
          - name: 网络月度事件报告
            description: 通过网络搜索采集指定主题的月度事件，通过深度分析生成月度事件洞察报告
            content: |
              通过网络搜索获取{param}当前年每月的重要的事件，通过深度分析生成洞察报告，要求：
              - 使用 @get_current_time 获取当前时间
              - 使用 @sequentialthinking 来规划所有的步骤，思考和分支
              - 可以使用 @bing_search 按照当前年逐月进行一汽的重要的事件搜索，每一轮Thinking之前都先搜索验证
              - 可以用 @crawl_webpage 来查看搜索到的网页详情
              - 思考轮数不低于5轮，且需要有发散脑暴意识，需要有思考分支
              - 每一轮需要根据查询的信息结果，反思自己的决策是否正确
              - 进行事件关联分析与结论形成 网络月度事件报告
              - 使用 @writeFile保存为html文件，并使用 @viewFileUrl返回预览地址
              
              > {param}为事件主题
          - name: http测试
            description: 自定义http服务测试
            content: classpath:skills/http.st
            load: false
          - name: 测试自动编译
            description: 测试自动编译，使用git拉取代码，maven编译，构建docker镜像并创建容器运行
            content: classpath:skills/package-docker.st
          - name: 测试自动E2E功能验证
            description: 测试使用浏览器对功能进行E2E测试，并生成验证报告
            content: classpath:skills/e2e.st
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  data:
#    redis:
#      host: localhost
#      port: 9379
#      password: 123456

logging:
  level:
    org:
      springframework:
        ai: DEBUG
server:
