package cn.wubo.spring.ai.loom.agent.schedule;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;

/**
 * H2 / JDBC-backed {@link ILoomScheduleExecutionRepository}.
 * <p>
 * Persists {@link LoomScheduleExecutionRecord} rows across application restarts.
 * Schema is also declared as a Flyway migration
 * ({@code V2.0__subtask_and_schedule.sql} — table {@code loom_schedule_execution}); this class additionally calls
 * {@link #ensureSchema()} defensively so the table is created even when Flyway
 * is bypassed.
 * </p>
 */
public class JdbcLoomScheduleExecutionRepository implements ILoomScheduleExecutionRepository {

    private static final Logger log = LoggerFactory.getLogger(JdbcLoomScheduleExecutionRepository.class);

    public static final String TABLE_NAME = "loom_schedule_execution";

    private static final String DDL = "CREATE TABLE IF NOT EXISTS " + TABLE_NAME + " ("
            + " execution_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + " task_name      VARCHAR(255) NOT NULL,"
            + " fire_time      TIMESTAMP(9) WITH TIME ZONE NOT NULL,"
            + " duration_ms    BIGINT NOT NULL,"
            + " success        BOOLEAN NOT NULL,"
            + " error_message  CLOB,"
            + " fired_by       VARCHAR(16) NOT NULL DEFAULT 'SCHEDULER'"
            + ")";

    private static final String DDL_INDEX_TASK_FIRE =
            "CREATE INDEX IF NOT EXISTS idx_loom_schedule_execution_task_fire"
                    + " ON " + TABLE_NAME + "(task_name, fire_time DESC)";

    private static final String DDL_INDEX_FIRE =
            "CREATE INDEX IF NOT EXISTS idx_loom_schedule_execution_fire"
                    + " ON " + TABLE_NAME + "(fire_time)";

    private static final String COLUMNS =
            " execution_id, task_name, fire_time, duration_ms, success, error_message, fired_by";

    private static final String INSERT_SQL =
            "INSERT INTO " + TABLE_NAME + " (task_name, fire_time, duration_ms, success, error_message, fired_by)"
                    + " VALUES (?, ?, ?, ?, ?, ?)";

    private final JdbcTemplate jdbc;

    public JdbcLoomScheduleExecutionRepository(DataSource dataSource) {
        this.jdbc = new JdbcTemplate(dataSource);
    }

    public JdbcLoomScheduleExecutionRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public void ensureSchema() {
        jdbc.execute(DDL);
        jdbc.execute(DDL_INDEX_TASK_FIRE);
        jdbc.execute(DDL_INDEX_FIRE);
        log.debug("JdbcLoomScheduleExecutionRepository schema ensured at {}", TABLE_NAME);
    }

    @Override
    public void save(LoomScheduleExecutionRecord r) {
        jdbc.update(INSERT_SQL,
                r.taskName(),
                Timestamp.from(r.fireTime() == null ? Instant.now() : r.fireTime()),
                r.durationMs(),
                r.success(),
                r.errorMessage(),
                r.firedBy() == null ? LoomScheduleExecutionRecord.FIRED_BY_SCHEDULER : r.firedBy());
    }

    @Override
    public List<LoomScheduleExecutionRecord> findByTaskName(String taskName, int limit) {
        if (taskName == null || taskName.isBlank()) return List.of();
        return jdbc.query(
                "SELECT " + COLUMNS + " FROM " + TABLE_NAME
                        + " WHERE task_name = ?"
                        + " ORDER BY fire_time DESC"
                        + (limit > 0 ? " LIMIT " + limit : ""),
                (rs, rowNum) -> mapRow(rs),
                taskName);
    }

    @Override
    public int countByTaskName(String taskName) {
        Integer n = jdbc.queryForObject(
                "SELECT COUNT(*) FROM " + TABLE_NAME + " WHERE task_name = ?",
                Integer.class, taskName);
        return n != null ? n : 0;
    }

    @Override
    public int trimTaskHistory(String taskName, int keepLast) {
        if (keepLast < 0) return 0;
        // Delete the (count - keepLast) oldest rows. H2 supports DELETE with subquery
        // for LIMIT-style behavior; we instead identify IDs first then bulk-delete.
        List<Long> idsToKeep = jdbc.query(
                "SELECT execution_id FROM " + TABLE_NAME
                        + " WHERE task_name = ?"
                        + " ORDER BY fire_time DESC"
                        + (keepLast > 0 ? " LIMIT " + keepLast : " LIMIT 0"),
                (rs, rowNum) -> rs.getLong(1),
                taskName);
        if (idsToKeep.isEmpty()) {
            // Either nothing to keep OR we wanted to delete all (keepLast==0).
            return jdbc.update("DELETE FROM " + TABLE_NAME + " WHERE task_name = ?", taskName);
        }
        // Build comma-separated list of IDs to retain.
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < idsToKeep.size(); i++) {
            if (i > 0) sb.append(',');
            sb.append(idsToKeep.get(i));
        }
        return jdbc.update(
                "DELETE FROM " + TABLE_NAME
                        + " WHERE task_name = ? AND execution_id NOT IN (" + sb + ")",
                taskName);
    }

    @Override
    public int deleteOlderThan(Instant cutoff) {
        if (cutoff == null) return 0;
        return jdbc.update(
                "DELETE FROM " + TABLE_NAME + " WHERE fire_time < ?",
                Timestamp.from(cutoff));
    }

    @Override
    public int deleteByUserAndConversation(String username, String conversationId) {
        if (username == null || username.isBlank()
                || conversationId == null || conversationId.isBlank()) {
            return 0;
        }
        // task_name format is loom-sched-{user}-{conv}-{friendlyName}; LIKE with
        // the user/conv prefix narrows to this conversation's tasks without
        // requiring a denormalized conversation_id column on this table.
        String prefix = "loom-sched-" + username + "-" + conversationId + "-";
        return jdbc.update(
                "DELETE FROM " + TABLE_NAME + " WHERE task_name LIKE ?",
                prefix + "%");
    }

    private static LoomScheduleExecutionRecord mapRow(java.sql.ResultSet rs) throws java.sql.SQLException {
        return new LoomScheduleExecutionRecord(
                rs.getLong("execution_id"),
                rs.getString("task_name"),
                rs.getTimestamp("fire_time").toInstant(),
                rs.getLong("duration_ms"),
                rs.getBoolean("success"),
                rs.getString("error_message"),
                rs.getString("fired_by"));
    }
}