package cn.wubo.loom.compile.core.strategy;

import cn.wubo.loom.compile.core.CompileAndDeployOperations;
import cn.wubo.loom.compile.core.CompileAndDeployOperations.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Maven / Java Spring Boot project build strategy.
 */
public record MavenBuildStrategy() implements BuildStrategy {

 @Override
 public List<String> markerFiles() {
 return List.of("pom.xml");
 }

 @Override
 public List<List<String>> buildCommands() {
 return List.of(
 List.of("mvn", "-B", "-e", "clean", "package", "-DskipTests"));
 }

 @Override
 public List<String> artifactCandidates() {
 return List.of("target");
 }

 @Override
 public boolean isLongRunning() {
 return true;
 }

 @Override
 public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
 File dockerfile = projectDir.resolve("Dockerfile").toFile();
 String entrypoint = CompileAndDeployOperations.toJsonArray(image.command());
 String content = String.format("""
 # Auto-generated by MavenBuildStrategy
 FROM %s
 WORKDIR /app
 COPY %s app.jar
 EXPOSE %d
 ENTRYPOINT %s
 """, image.image(), artifact, containerPort, entrypoint);
 Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
 return dockerfile;
 }

 @Override
 public Path findArtifact(Path targetDir) {
 File jar = pickJarFromTarget(targetDir);
 return jar != null ? jar.toPath() : null;
 }

 private static File pickJarFromTarget(Path target) {
 File dir = target.toFile();
 File[] jars = dir.listFiles((d, name) -> name.endsWith(".jar") && !name.endsWith(".original.jar")
 && !name.endsWith("-sources.jar") && !name.endsWith("-javadoc.jar"));
 if (jars == null || jars.length == 0) return null;
 Arrays.sort(jars, Comparator.comparingLong(File::length).reversed());
 return jars[0];
 }
}
