package cn.wubo.loom.compile.core.strategy;

import cn.wubo.loom.compile.core.CompileAndDeployOperations;
import cn.wubo.loom.compile.core.CompileAndDeployOperations.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Node.js backend (long-running process) build strategy.
 * Express / Koa / NestJS / Nuxt SSR / Next custom server.
 */
public record NpmBackendBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("package.json");
    }

    @Override
    public List<List<String>> buildCommands() {
        return List.of(
                List.of("npm", "ci", "--no-audit", "--no-fund"),
                List.of("npm", "run", "build")
        );
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of("dist", "build", ".next");
    }

    @Override
    public boolean isLongRunning() {
        return true;
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = CompileAndDeployOperations.toJsonArray(image.command());
        String content = String.format("""
                # Auto-generated by NpmBackendBuildStrategy
                FROM %s
                WORKDIR /app
                COPY package*.json ./
                RUN npm ci --omit=dev --no-audit --no-fund
                COPY %s ./%s
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), artifact, artifact, containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }
}
