package cn.wubo.loom.compile.core.strategy;

import cn.wubo.loom.compile.core.CompileAndDeployOperations;
import cn.wubo.loom.compile.core.CompileAndDeployOperations.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Node.js frontend (static artifact -> nginx) build strategy.
 * Vue / React / SvelteKit / Astro static build / Next static export.
 */
public record NpmFrontendBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("package.json");
    }

    @Override
    public List<List<String>> buildCommands() {
        return List.of(
                List.of("npm", "ci", "--no-audit", "--no-fund"),
                List.of("npm", "run", "build")
        );
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of("dist", "build", ".next");
    }

    @Override
    public boolean isLongRunning() {
        return false;
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = CompileAndDeployOperations.toJsonArray(image.command());
        String content = String.format("""
                # Auto-generated by NpmFrontendBuildStrategy
                FROM %s
                RUN rm -rf /usr/share/nginx/html/*
                COPY %s /usr/share/nginx/html/
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), artifact, containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }
}
