package cn.wubo.loom.compile.core.strategy;

import cn.wubo.loom.compile.core.CompileAndDeployOperations;
import cn.wubo.loom.compile.core.CompileAndDeployOperations.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Python backend build strategy (Flask / FastAPI / Django).
 */
public record PythonBuildStrategy() implements BuildStrategy {

 @Override
 public List<String> markerFiles() {
 return List.of("requirements.txt", "pyproject.toml");
 }

 @Override
 public List<List<String>> buildCommands() {
 return List.of();
 }

 @Override
 public List<String> artifactCandidates() {
 return List.of(".");
 }

 @Override
 public boolean isLongRunning() {
 return true;
 }

 @Override
 public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
 File dockerfile = projectDir.resolve("Dockerfile").toFile();
 String entrypoint = CompileAndDeployOperations.toJsonArray(image.command());
 String content = String.format("""
 # Auto-generated by PythonBuildStrategy
 FROM %s
 WORKDIR /app
 COPY requirements.txt ./
 RUN pip install --no-cache-dir -r requirements.txt
 COPY . .
 EXPOSE %d
 ENTRYPOINT %s
 """, image.image(), containerPort, entrypoint);
 Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
 return dockerfile;
 }
}
