-- =============================================================
-- Persistent event log for schedule fire attempts.
-- =============================================================
-- 背景：之前 schedule 触发后的"这次执行怎么样"完全活在 flex-schedule
--      的 InMemoryExecutionHistory 里,重启即丢。one_shot 触发后还
--      被 loom-agent 自己的 after-fire cleanup 直接从 loom_scheduled_task
--      删掉,等于彻底消失,前端按 conversation 看"这个对话产生的所有
--      定时执行"什么都看不到。
--
-- 新增事件表,每次触发(包括成功 / 失败 / 异常)写一行。loom_scheduled_task
-- 保留 schedule 的"声明",不再被 one_shot 触发后清理。两者解耦后:
--   - loom_scheduled_task        -- "用户注册了什么 schedule"
--   - loom_schedule_execution    -- "每次触发发生了什么"
-- 写入频率 / 保留策略可以独立配置。
--
-- fired_by 列预留 'SCHEDULER' / 'MANUAL' 两种值,未来如果加"手动触发一次"
-- 工具能直接复用本表。
-- =============================================================

CREATE TABLE loom_schedule_execution (
    execution_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name      VARCHAR(255) NOT NULL,                  -- 对应 loom_scheduled_task.task_name(无 FK 约束,因为 one_shot 取消 / 过期可能把声明行删掉但执行历史保留)
    fire_time      TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    duration_ms    BIGINT NOT NULL,
    success        BOOLEAN NOT NULL,
    error_message  CLOB,
    fired_by       VARCHAR(16) NOT NULL DEFAULT 'SCHEDULER' -- 'SCHEDULER' / 'MANUAL'(预留)
);

CREATE INDEX idx_loom_schedule_execution_task_fire
    ON loom_schedule_execution(task_name, fire_time DESC);

CREATE INDEX idx_loom_schedule_execution_fire
    ON loom_schedule_execution(fire_time);