-- =============================================================
-- Spring AI LoomAgent — V2.0：子任务 + 定时任务 + 会话侧边栏元数据
-- =============================================================
-- 本迁移把历史增量 V12~V17 合并成单一脚本。V1.0__init.sql（基础表 + 默认 admin）
-- 保持不动；本文件只追加 V2.0 引入的新表 / 列。
--
--   - loom_scheduled_task       定时任务声明（原 V13）
--   - loom_schedule_execution   定时任务执行历史（原 V16）
--   - loom_subtask_history      子任务执行历史（原 V15）
--   - user_conversation 三列    侧边栏元数据 title/created_at/updated_at（原 V17，ALTER）
--   - SPRING_AI_CHAT_MEMORY     conversation_id 加宽到 255（原 V14）
--
-- 已废弃：旧 V12 的 flex_scheduled_task 不再创建 —— flex-schedule 1.x 已改为纯内存
--        实现（InMemoryTaskRepository），无 JdbcTaskRepository，该表零引用。这里保留
--        一条防御性 DROP IF EXISTS 以清理可能残留的旧表。
-- =============================================================


-- ============== 清理已废弃的 flex_scheduled_task（原 V12） ==============
DROP TABLE IF EXISTS flex_scheduled_task;
DROP INDEX IF EXISTS idx_flex_scheduled_task_created_at;


-- =============================================================
-- 定时任务：声明表（原 V13）
-- =============================================================
-- loom-agent 自己持久化 prompt 触发的定时子任务声明。flex-schedule 1.x 纯内存,
-- 重启即丢,所以启动时由 ScheduleRestoreListener 读本表并通过 flex-schedule 的
-- TaskBuilder.createdAt(...).register(...) 重灌,保留原 createdAt 以便 max-lifetime
-- (默认 72h)上限跨重启仍生效。

CREATE TABLE loom_scheduled_task (
    task_name             VARCHAR(255) PRIMARY KEY,
    schedule_type         VARCHAR(20) NOT NULL,                     -- 'cron' | 'fixed_delay' | 'fixed_rate' | 'one_shot'
    cron_expression       VARCHAR(100),                              -- when schedule_type = 'cron'
    interval_seconds      BIGINT,                                    -- when schedule_type IN ('fixed_delay', 'fixed_rate')
    initial_delay_seconds BIGINT,                                    -- nullable
    one_shot_delay_seconds BIGINT,                                   -- when schedule_type = 'one_shot'
    prompt                CLOB NOT NULL,                             -- the sub-task prompt run on each fire
    username              VARCHAR(64) NOT NULL,
    conversation_id       VARCHAR(64) NOT NULL,
    paused                BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(9) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_loom_scheduled_task_user_conv
    ON loom_scheduled_task(username, conversation_id);
CREATE INDEX idx_loom_scheduled_task_created_at
    ON loom_scheduled_task(created_at);


-- =============================================================
-- 定时任务：执行历史（原 V16）
-- =============================================================
-- 每次触发(成功 / 失败 / 异常)写一行。与 loom_scheduled_task 解耦:
--   - loom_scheduled_task     -- "用户注册了什么 schedule"
--   - loom_schedule_execution -- "每次触发发生了什么"
-- 无 FK：one_shot 取消 / 过期会删声明行,但执行历史保留。

CREATE TABLE loom_schedule_execution (
    execution_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name      VARCHAR(255) NOT NULL,
    fire_time      TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    duration_ms    BIGINT NOT NULL,
    success        BOOLEAN NOT NULL,
    error_message  CLOB,
    fired_by       VARCHAR(16) NOT NULL DEFAULT 'SCHEDULER'          -- 'SCHEDULER' / 'MANUAL'(预留)
);
CREATE INDEX idx_loom_schedule_execution_task_fire
    ON loom_schedule_execution(task_name, fire_time DESC);
CREATE INDEX idx_loom_schedule_execution_fire
    ON loom_schedule_execution(fire_time);


-- =============================================================
-- 子任务执行历史（原 V15）
-- =============================================================
-- SubTaskRegistry.markFinished 走 writeHook 双写到这张表,重启不丢;
-- 前端按 (username, conversation_id) 看"这个对话发起的所有子任务"。
-- status 沿用 SubTaskStatus 枚举(RUNNING/COMPLETED/FAILED/CANCELLED),
-- 用 VARCHAR(16) 而非 CHECK 以便未来扩展枚举值。

CREATE TABLE loom_subtask_history (
    subtask_id      VARCHAR(64)  PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    conversation_id VARCHAR(64)  NOT NULL,
    prompt          CLOB         NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    started_at      BIGINT       NOT NULL,                -- System.currentTimeMillis
    finished_at     BIGINT       NOT NULL,
    error_message   CLOB,
    result_text     CLOB
);
CREATE INDEX idx_loom_subtask_history_user_conv
    ON loom_subtask_history(username, conversation_id);
CREATE INDEX idx_loom_subtask_history_user_finished
    ON loom_subtask_history(username, finished_at DESC);


-- =============================================================
-- 会话侧边栏元数据（原 V17）
-- =============================================================
-- 给 V1.0 建的 user_conversation 追加三列：持久化空会话 + 用户自定义标题。

ALTER TABLE user_conversation ADD COLUMN title VARCHAR(100);
ALTER TABLE user_conversation ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_conversation ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX idx_user_conv_created ON user_conversation(username, deleted_at, created_at DESC);


-- =============================================================
-- 扩展 SPRING_AI_CHAT_MEMORY.conversation_id 列宽（原 V14）
-- =============================================================
-- Spring AI 的 JdbcChatMemoryRepository(initialize-schema=always)把
-- conversation_id 建成 VARCHAR(36)。而子任务用
-- "{parentConversationId}--sub--{subTaskId}" 作为 conversation_id(67+ 字符),
-- 会触发 "Value too long for column ... VARCHAR(36)"。
--
-- Flyway 一定在 Spring AI 的 schema init 之后跑(DataSourceInitializerDependsOn-
-- PostProcessor 加了 @DependsOn),所以这里看到的表已是 VARCHAR(36)。全新空库若
-- 还没发过 chat 请求,该表尚不存在 —— 先防御性建表(Spring AI 同款 schema),再 ALTER。

CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY (
    conversation_id VARCHAR(36) NOT NULL,
    content LONGVARCHAR NOT NULL,
    type VARCHAR(10) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SPRING_AI_CHAT_MEMORY ALTER COLUMN conversation_id VARCHAR(255);
