-- =============================================================
-- V4.0：全量对话流（重写会话日志）
-- =============================================================
-- 背景：控制台 conversation.html 重写为「单次会话全量时间线」视图，
-- 需 tool_call / subtask / schedule 等多源数据。当前 token_usage 表只记录
-- turn 级别的 token 统计，缺少 tool 调用入参/返回，无法在控制台展示完整
-- 对话流转。
--
-- 改动：
--   1. 新建 loom_tool_call_log   工具调用入参/返回/耗时（替代从 chat_memory.metadata
--                                反向解析 JSON 的脆弱方式）
--   2. DROP token_usage          旧 turn 统计表（V4.0 后统计从 chat_memory + tool_call_log
--                                实时聚合，不再维护重复数据）
--   3. 加索引                    tool_call_log 按 conversation_id + created_at 复合索引，
--                                支持 conversation.html 时间线 / 分页高效查询
-- =============================================================


-- ============== 1. 新建 loom_tool_call_log ==============
CREATE TABLE loom_tool_call_log (
    log_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    username        VARCHAR(64)  NOT NULL,
    tool_call_id    VARCHAR(128) NOT NULL,              -- Spring AI tool call id，用于和 ToolResponseMessage 关联
    tool_name       VARCHAR(128) NOT NULL,
    arguments_json  CLOB,                              -- 工具入参 JSON（截断 64KB）
    result_text     CLOB,                              -- 工具返回值（截断 64KB）
    result_is_error BOOLEAN     NOT NULL DEFAULT FALSE, -- 是否错误返回
    duration_ms     BIGINT,
    created_at      TIMESTAMP(9) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_loom_tool_call_log_conv_time
    ON loom_tool_call_log(conversation_id, created_at);
CREATE INDEX idx_loom_tool_call_log_user_time
    ON loom_tool_call_log(username, created_at DESC);


-- ============== 2. DROP token_usage ==============
-- 旧 turn 级 token 统计表。V4.0 后：
--   - stats.html   全局月度 token   从 chat_memory 实时聚合
--   - user.html    用户最近 6 月   从 chat_memory 实时聚合
--   - conversation.html 单会话     从 chat_memory 实时聚合
-- chat_memory 中 AssistantMessage.metadata 已存 usage metadata
-- （prompt_tokens / completion_tokens / total_tokens），无需重复落库。
DROP TABLE IF EXISTS token_usage;
DROP INDEX IF EXISTS idx_token_usage_conv_time;
DROP INDEX IF EXISTS idx_token_usage_user_time;


-- ============== 3. 新建 loom_chat_usage（V5.0 合并） ==============
-- V4.0 原计划从 chat_memory 反推 usage metadata，交付时发现 AssistantMessage.content
-- 只持久化文本、metadata 未落库 → 改显式记录。每次 LLM 流响应在 SseController
-- 写一行，ChatUsageService 查这张表（不依赖 chat_memory 反推）。
CREATE TABLE loom_chat_usage (
    log_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   VARCHAR(255) NOT NULL,
    username          VARCHAR(64)  NOT NULL,
    prompt_tokens     BIGINT       NOT NULL DEFAULT 0,
    completion_tokens BIGINT       NOT NULL DEFAULT 0,
    total_tokens      BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP(9) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_loom_chat_usage_user_time
    ON loom_chat_usage(username, created_at DESC);
CREATE INDEX idx_loom_chat_usage_conv_time
    ON loom_chat_usage(conversation_id, created_at);


-- ============== 4. 新建 loom_chat_reasoning（V5.1 合并） ==============
-- 背景：chat_memory 同样不持久化 metadata.reasoningContent（DashScope
-- enable_thinking 模式下的 AI 思考）。SseController 在流结束 doOnComplete
-- 时一次性写完整 reasoning；ConversationFlowService 优先读这张表，绑到
-- conversation.html 第一条 ASSISTANT 卡片的"思考"折叠区。
CREATE TABLE loom_chat_reasoning (
    conversation_id VARCHAR(255) PRIMARY KEY,
    reasoning_text  CLOB,
    created_at      TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(9) WITH TIME ZONE NOT NULL
);
