package cn.wubo.spring.ai.loom.agent.tool.compile.strategy;

import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool;
import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Maven / Java Spring Boot 项目的构建策略。
 * <p>
 * 编译：{@code mvn clean package -DskipTests}（多模块走 mvn -f 显式指定 pom）。
 * 产物：{@code target/} 下体积最大的非 {@code .original.jar} / {@code -sources.jar} jar。
 * Dockerfile：{@code COPY target/<jar> app.jar} + Java ENTRYPOINT。
 */
public record MavenBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("pom.xml");
    }

    @Override
    public List<List<String>> buildCommands() {
        return List.of(
                List.of("mvn", "-B", "-e", "clean", "package", "-DskipTests"));
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of("target");
    }

    @Override
    public boolean isLongRunning() {
        return true;
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = DefaultCompileAndDeployTool.toJsonArray(image.command());
        String content = String.format("""
                # Auto-generated by MavenBuildStrategy
                FROM %s
                WORKDIR /app
                COPY %s app.jar
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), artifact, containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }

    /**
     * 在 {@code target/} 下挑体积最大的 Spring Boot fat jar，
     * 跳过 repackage 前的 {@code .original.jar} / {@code -sources.jar} / {@code -javadoc.jar}。
     *
     * @return 选中 jar 的绝对路径；找不到返回 null
     */
    @Override
    public Path findArtifact(Path targetDir) {
        File jar = pickJarFromTarget(targetDir);
        return jar != null ? jar.toPath() : null;
    }

    /**
     * 在 {@code target/} 下挑体积最大的 Spring Boot fat jar。
     * 跳过 {@code .original.jar} / {@code -sources.jar} / {@code -javadoc.jar}。
     * <p>
     * 选最大 jar 属于 Maven 专有行为，放在 strategy 内（这里）而不是
     * {@code DefaultCompileAndDeployTool} 主流程；原主流程里的同名 helper 已废弃。
     */
    private static File pickJarFromTarget(Path target) {
        File dir = target.toFile();
        File[] jars = dir.listFiles((d, name) -> name.endsWith(".jar") && !name.endsWith(".original.jar")
                && !name.endsWith("-sources.jar") && !name.endsWith("-javadoc.jar"));
        if (jars == null || jars.length == 0) return null;
        // 取体积最大的（Spring Boot repackage jar 一定比普通 jar 大）
        Arrays.sort(jars, Comparator.comparingLong(File::length).reversed());
        return jars[0];
    }
}
