package cn.wubo.spring.ai.loom.agent.tool.compile.strategy;

import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool;
import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Node.js 后端（长驻进程）构建策略。
 * <p>
 * 适用：Express / Koa / NestJS / Nuxt SSR / Next custom server 等 Node 长驻服务。
 * 编译：{@code npm ci} → {@code npm run build}。
 * 产物：{@code dist/} > {@code build/} > {@code .next/}（第一个存在者）。
 * Dockerfile：{@code node:20-alpine} + COPY package*.json + COPY dist + {@code npm ci --omit=dev} + node ENTRYPOINT。
 */
public record NpmBackendBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("package.json");
    }

    @Override
    public List<List<String>> buildCommands() {
        return List.of(
                List.of("npm", "ci", "--no-audit", "--no-fund"),
                List.of("npm", "run", "build")
        );
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of("dist", "build", ".next");
    }

    @Override
    public boolean isLongRunning() {
        return true;
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = DefaultCompileAndDeployTool.toJsonArray(image.command());
        // artifact 是相对 projectDir 的目录名（dist / build / .next）
        String content = String.format("""
                # Auto-generated by NpmBackendBuildStrategy
                FROM %s
                WORKDIR /app
                COPY package*.json ./
                RUN npm ci --omit=dev --no-audit --no-fund
                COPY %s ./%s
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), artifact, artifact, containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }
}
