package cn.wubo.spring.ai.loom.agent.tool.compile.strategy;

import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool;
import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Node.js 前端（静态产物 → nginx）构建策略。
 * <p>
 * 适用：Vue / React / SvelteKit / Astro 静态构建 / Next static export 等输出
 * 纯静态 HTML/CSS/JS 的前端项目。
 * 编译：{@code npm ci} → {@code npm run build}（与后端共用）。
 * 产物：{@code dist/} > {@code build/} > {@code .next/out}（第一个存在者）。
 * Dockerfile：{@code nginx:alpine} + COPY 整个产物目录到 {@code /usr/share/nginx/html}。
 * <p>
 * 端口约定：{@code containerPort=80}（nginx 默认）；{@code port} 由用户在对话指定宿主机映射。
 */
public record NpmFrontendBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("package.json");
    }

    @Override
    public List<List<String>> buildCommands() {
        return List.of(
                List.of("npm", "ci", "--no-audit", "--no-fund"),
                List.of("npm", "run", "build")
        );
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of("dist", "build", ".next");
    }

    @Override
    public boolean isLongRunning() {
        return false;  // nginx 静态服务
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = DefaultCompileAndDeployTool.toJsonArray(image.command());
        String content = String.format("""
                # Auto-generated by NpmFrontendBuildStrategy
                FROM %s
                # 删掉 nginx 默认站点，把前端产物放进去
                RUN rm -rf /usr/share/nginx/html/*
                COPY %s /usr/share/nginx/html/
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), artifact, containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }
}
