package cn.wubo.spring.ai.loom.agent.tool.compile.strategy;

import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool;
import cn.wubo.spring.ai.loom.agent.tool.compile.DefaultCompileAndDeployTool.ResolvedImage;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Python 后端构建策略（Flask / FastAPI / Django）。
 * <p>
 * 适用：单文件 Python 后端（{@code app.py} / {@code main.py}）+ {@code requirements.txt}。
 * 编译：<b>无独立 build 阶段</b>（pip install 在 Dockerfile 内做）。
 * 产物：项目根目录（{@code .}）—— COPY 整个项目。
 * Dockerfile：{@code python:3.12-slim} + COPY requirements.txt + {@code pip install} + COPY . + ENTRYPOINT。
 * <p>
 * 启动命令建议：
 * <ul>
 *   <li>FastAPI: {@code ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]}</li>
 *   <li>Flask: {@code ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "app:app"]}</li>
 *   <li>Django: {@code ["gunicorn", "mysite.wsgi", "-b", "0.0.0.0:8000"]}</li>
 * </ul>
 * 容器内端口约定 {@code 8000}（uvicorn / gunicorn 默认）。
 */
public record PythonBuildStrategy() implements BuildStrategy {

    @Override
    public List<String> markerFiles() {
        return List.of("requirements.txt", "pyproject.toml");
    }

    @Override
    public List<List<String>> buildCommands() {
        // 无 build 阶段 —— pip install 在 Dockerfile 内做（利用 Docker 层缓存）
        return List.of();
    }

    @Override
    public List<String> artifactCandidates() {
        return List.of(".");
    }

    @Override
    public boolean isLongRunning() {
        return true;
    }

    @Override
    public File writeDockerfile(Path projectDir, ResolvedImage image, int containerPort, String artifact) throws IOException {
        File dockerfile = projectDir.resolve("Dockerfile").toFile();
        String entrypoint = DefaultCompileAndDeployTool.toJsonArray(image.command());
        String content = String.format("""
                # Auto-generated by PythonBuildStrategy
                FROM %s
                WORKDIR /app
                # 优先装依赖（层缓存友好）
                COPY requirements.txt ./
                RUN pip install --no-cache-dir -r requirements.txt
                # 再 COPY 源码（频繁改动不破坏依赖层）
                COPY . .
                EXPOSE %d
                ENTRYPOINT %s
                """, image.image(), containerPort, entrypoint);
        Files.writeString(dockerfile.toPath(), content, StandardCharsets.UTF_8);
        return dockerfile;
    }
}
